import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="min-h-screen w-full overflow-hidden flex flex-col items-center relative px-4 md:px-0 py-16">
          {/* Background paralax image */}
          <div className="absolute ml-6 md:ml-0 -right-1/2 md:-right-0 md:-left-[55%] md:top-1/2 md:-translate-y-1/2">
            <Image
              src="/accets/images/eye-shape-teal@2x.avif"
              alt="bg-image"
              width={2040}
              height={1150}
            />
          </div>
          <div className="overflow-hidden relative w-full min-h-screen flex flex-col justify-center items-center">
            {/* Image/video container */}
            <div className="overflow-hidden md:absolute md:top-1/2 md:-translate-y-1/2 md:-left-[30%] md:w-3/4 h-[90%] rounded-xl shadow-light border border-black border-opacity-10">
              <video
                src="/accets/videos/real-time-collab-visual-v90.mp4"
                autoPlay
                loop
                muted
              ></video>
            </div>
            {/* Info container */}
            <div className="container max-w-6xl mx-auto flex justify-between md:gap-x-20">
              <div className="md:flex-1" />
              <div className="flex flex-1 flex-col gap-y-20 mt-20 md:mt-0">
                <div className="flex flex-col gap-y-6 px-5 md:px-0">
                  <h2 className="text-dark font-black text-subtitleMobile leading-subtitleMobile md:text-subtitleDesctop md:leading-subtitleDesctop">
                    The all-in-one designer’s toolkit
                  </h2>
                  <p className="text-dark font-medium text-base leading-6 md:text-lg md:leading-7">
                    More than just UI design tools – if you’re collaborating on
                    new concepts, building beautiful prototypes or crafting the
                    perfect app icon, we’ve got your whole design process
                    covered.
                  </p>
                </div>
                <div className="flex flex-col gap-y-8">
                  <div className="image-area">
                    <Image
                      src="/accets/images/native@2x.avif"
                      alt="image1"
                      width={524}
                      height={216}
                    />
                  </div>
                  <div className="flex flex-col gap-y-6 px-5 md:px-0">
                    <div className="flex flex-col gap-y-2">
                      <h3 className="text-dark font-bold text-lg leading-7">
                        Native macOS editor
                      </h3>
                      <p className="text-dark font-medium text-base leading-6">
                        Create your best work with an intuitive UI, thoughtful
                        features and all the benefits you’d expect from a great
                        Mac app (like support for P3 color profiles, native font
                        rendering, and super-fast Apple Silicon performance).
                      </p>
                    </div>
                    <Link
                      href="/"
                      className="text-dark font-bold text-base leading-6 flex items-center gap-x-1"
                    >
                      Explore your design toolkit
                      <Image
                        src="/accets/icons/arrow-right.svg"
                        alt="right-arrow"
                        width={24}
                        height={24}
                        className="opacity-30"
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
